version: 2.1
orbs:
  codecov: codecov/codecov@3.2.3
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: python -m pip install -r requirements.txt
      - run:
          name: Install additional tools
          command: python -m pip install pytest==6.2.2 pytest-cov==2.12.1
      - run:
          name: Run tests
          command: python -m pytest --cov=auto_heuristic
      - codecov/upload
