version: 2.1
orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --cov=./ --cov-config=.coveragerc --durations=5
      - codecov/upload
